### ISSUE TITLE
Menu label and shortcuts overlap

### ISSUE THREAD

**Issue by tastytea** [MasterQ32/kristall#1]
Version: 425f9d41cd337133d5677744eef937a8a2a61212
Qt version: 5.14.2
OS: Gentoo Linux

“New Tab” and “Close Tab” overlap with their shortcuts in the menu.

![screenshot_kristall_menu](https://user-images.githubusercontent.com/3681516/83967634-b6f7be80-a8c3-11ea-9fab-2af74e1a82ca.png)

**Comment by MasterQ32** [comment]
It looks like the latest master does not contain that bug anymore. Can you verify this?
