### ISSUE TITLE
Add  libssl-dev  to "Notes for Ubuntu 20.04" subsection

### ISSUE THREAD

**Issue by GiovanniMoretti** [MasterQ32/kristall#10]
The build failed on a fairly pristine install of Ubuntu Mate 20.04. Installing the libssl-dev package fixed it.
It's possible this is specific to the Mate flavour of Ubuntu, but having this as a recommended addition it won't hurt for all flavours.

**Comment by MasterQ32** [comment]
Yep, good idea!
