### ISSUE TITLE
Relative url bug

### ISSUE THREAD

**Issue by mikejzx** [MasterQ32/kristall#126]
To reproduce
* Navigate to gemini://rawtext.club:1965/~sloum/geminilist/
* Click any link on the page
* Navigate back to the original site. The cached version of the page will be displayed
* In the URL bar remove the trailing slash (if there is one) from the site so that it becomes gemini://rawtext.club:1965/~sloum/geminilist.
* Click any link on the page again. You will be presented with a 'resource not found' error, because the slash is missing, so QUrl::resolved in the renderer code creates the wrong URL.

Attempted to fix in 6018876 but this commit caused other breakages so it had to be reverted

**Comment by krkk** [comment]
We can partly revert 50729c19ebf75ab91ee285fe7af86abbdaec411c and cross fingers that sites will redirect us back to a cached page (which gemini://rawtext.club/~sloum/geminilist seems does that).
