### ISSUE TITLE
feature request: --new-tab

### ISSUE THREAD

**Issue by kkabrams** [MasterQ32/kristall#139]
I know this might be difficult to do cross-platform, but it'd be awesome if I could run kristall --new-tab [someurl] and it'd open in an already running kristall instead of making a new window. not sure what should happen is there's two kristall windows already open though.

**Comment by mikejzx** [comment]
I think that opening in new tab should actually be the default behaviour. We can then instead add a `--new-window` option in case a user wants to open in a new window.

**Comment by MasterQ32** [comment]
This feature *was* easy to implement in Qt4 with `QtSingleApplication`, nowadays the recommended way seems to be the use of a [`QLocalSocket`](https://doc.qt.io/qt-5/qlocalsocket.html) and [`QLocalServer`](https://doc.qt.io/qt-5/qlocalserver.html)
