### ISSUE TITLE
Question: How to use categories in bookmarks?

### ISSUE THREAD

**Issue by linuxcult** [MasterQ32/kristall#148]
I like the kristall browser a lot, but I couldn't figure out, how to categorize my bookmarks.

I've seen other people doing it, but I don't know how.

Any help would be great!

**Comment by MasterQ32** [comment]
You can rightclick and use "Create new group", then you can use drag and drop to categorize your bookmarks

**Comment by linuxcult** [comment]
Hmm.. Yes, that sounds simple. But unfortunatly rightclick in the bookmarks window doesn't open any menu. And when I rightclick on a bookmark it only shows the menu items "open here" and "open in new tab". Dragging them is not possible.

I'm using version 0.3-0 from the arch user repository, if that explains anything.

**Comment by linuxcult** [comment]
Oh boy! I installed the git version from the arch user repository (kristall-git) now, and it works fantastically!

**Comment by MasterQ32** [comment]
Yeah, it's really time for a new tagged release. I should probaby just click the "Tag" button…
