### ISSUE TITLE
Github Action - Building Windows

### ISSUE THREAD

**Issue by krixano** [MasterQ32/kristall#15]
The Windows build is getting an error because it can't see the `cl` compiler. All you have to do to fix this is call vcvars64 (or vcvars32) batch file that microsoft provides to setup the compiler environment.

```
call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat
```

**Comment by MasterQ32** [comment]
Resolved windows build with a custom CI solution instead of using github ci.
