### ISSUE TITLE
Emoji are shown as “question marks”

### ISSUE THREAD

**Issue by tastytea** [MasterQ32/kristall#16]
Example from gemini.circumlunar.space¹, Kristall vs. Castor:

![screenshot_2020-06-18T17-52-43](https://user-images.githubusercontent.com/3681516/85043709-f3ad9a80-b18c-11ea-8301-304073bec37d.png "Screenshot Kristall")
![screenshot_2020-06-18T17-53-25](https://user-images.githubusercontent.com/3681516/85043711-f4463100-b18c-11ea-9f73-15b0d95c1d19.png "Screenshot Castor")

The response line is `20 text/gemini` and the charset seems to be UTF-8 (my terminal displays it correctly).

The font is “Source Serif Pro”, which doesn't support “😞”, in both browsers. The emoji in Castor is taken from “Noto Emoji”, as configured via Fontconfig.

¹ <gemini://gemini.circumlunar.space/~solderpunk/cornedbeef/why-not-just-use-a-subset-of-http-and-html.gmi>

**Comment by MasterQ32** [comment]
Are you using the experimental *text highlights* feature?

**Comment by MasterQ32** [comment]
If yes, it should be fixed in 9a5c0b8ba8595b9084ad8dc27884b0cbc691459c

**Comment by tastytea** [comment]
Yes, it only happened with *text highlights* enabled and it works with 9a5c0b8ba8595b9084ad8dc27884b0cbc691459c.
