### ISSUE TITLE
Feature request: render and display .tex files in line

### ISSUE THREAD

**Issue by tidux** [MasterQ32/kristall#161]
Per the Gemini mailing list, there is [some discussion](https://lists.orbitalfox.eu/archives/gemini/2021/005299.html) of how best to provide mathematical notation for people that want to use Gemini as a platform to share research and don't want to be limited to whole PDF/HTML pages for showing equations.  In poking around for Qt math libraries, it looks like https://github.com/jkriege2/JKQtPlotter is a good option with no extra dependencies.

**Comment by MasterQ32** [comment]
I don't think putting a tex parser into kristall is a good idea. It would encourage people to actually use or embed tex files in gemini text and making it impossible to read those files in other clients (terminal based ones for example)
