### ISSUE TITLE
unable to use veronica search engine

### ISSUE THREAD

**Issue by bmorel** [MasterQ32/kristall#165]
Trying to use [veronica](gopher://gopher.floodgap.com/1/v2) search engine:

```
Unsupported Media Type!

Kristall cannot display the requested document.

To view this media, use the File menu to save it to your local drive, then open the saved file in another program that can display the document for you.
--

Details:
- MIME type: application/octet-stream
- Size: 415 B
```

(note that I had to copy/past each area one after one to report full message, it might be another bug/feature request here)

Tried as of 291bfd02b4cda9c4d3fd25da01bbc539b9308a61

**Comment by MasterQ32** [comment]
This sounds like either a bug in Kristall or a bug in the webserver of veronica. Can you provide the link you requested?

**Comment by bmorel** [comment]
sorry, I'm pretty sure I did, but... here it is: gopher://gopher.floodgap.com:70/7/v2/vs
