### ISSUE TITLE
allow to disable emoji fonts

### ISSUE THREAD

**Issue by bmorel** [MasterQ32/kristall#166]
Emoji fonts (notably Noto) can sometimes lead to problems by taking precedence over text fonts, making text hard to read for arguably nicer look.
Allowing users to disable completely those fonts within the user interface seems a better "fix" than to patch the code.

Ideally, the problem itself should be fixed, but since it's non-trivial and depends on system, I think it's better to have a user-friendly workaround before, plus, this might be wished anyway even without this problem.

**Comment by mikejzx** [comment]
I think this is a good idea. Especially since on Windows the emoji fonts are the cause of some really annoying problems - it'd be wise to disable them by default on those systems, I think at least for now.

**Comment by bmorel** [comment]
> I've noticed personally that using a font with Kristall that isn't actually available on the system (happens usually if you try to use the included preset styles) then the emoji font is used as a fallback

The fonts where shown by kristall, so I assume they're on the system, especially since changing them changed the text's appearance. I even tried with "source code pro" which I use in my terminals notably, so I'm sure it's here and that it can display glyphs between 0 and 9 (included). There probably something which takes precedence, somehow.

Since I didn't mentioned it, I'm using Debian 10 "buster".
