### ISSUE TITLE
Incorrect handling of status code 30

### ISSUE THREAD

**Issue by Sgiath** [MasterQ32/kristall#199]
When server sends response: `30 /\r\n` the browser should redirect to home page of the server but Kristall instead shows "Protocol Violation" page with error code "Line is too short for valid protocol".

I believe this response is valid one since status code 30 allows returning relative paths. Other Gemini browsers (for example Amfora) handle this response correctly.

**Comment by MasterQ32** [comment]
I cannot reproduce this locally:
```
echo -ne '30 /\r\n' | ncat --listen --ssl --ssl-cert cert.pem --ssl-key key.pem  1965
echo -ne '20 text/plain\r\nsuccess' | ncat --listen --ssl --ssl-cert cert.pem --ssl-key key.pem  1965
```
It works and properly redirects. Which version of Kristall are you using?

**Comment by Sgiath** [comment]
I am using version 0.3-0 from Arch Linux AUR repository and I can reproduce it locally with your commands.

**Comment by MasterQ32** [comment]
Ah yeah. 0.3.0 is outdated by nearly a year and roughly 400 commits. You should use the nightly download or build it yourself

**Comment by Sgiath** [comment]
Oh I didn't realized that. Sorry for wasting your time.
