### ISSUE TITLE
kristall does not take arguments

### ISSUE THREAD

**Issue by tastytea** [MasterQ32/kristall#2]
Version: 425f9d41cd337133d5677744eef937a8a2a61212
Qt version: 5.14.2
OS: Gentoo Linux

I tried to get kristall to open a page immediately after starting with `kristall gemini://random-projects.net/blog/2020-06-07-kristall.gemini` but it ignored my request.

**Comment by MasterQ32** [comment]
Thanks, i'll put it on the todo list
