### ISSUE TITLE
Impossible to navigate through the file menu bar without a mouse

### ISSUE THREAD

**Issue by mdrln** [MasterQ32/kristall#200]
Please use QMenuBar instead, the current system doesn't support keybinds like Alt+F to open the File button and other buttons. This makes it difficult to impossible for those who choose not or are unable to use a mouse to use the file menu bar properly. Thank you and have a good day. :)

**Comment by MasterQ32** [comment]
The menu is a `QMenuBar`, i can navigate it by tapping `Alt`, then using the arrow keys. I assume you want to have shortcuts via underlined characters?
