### ISSUE TITLE
Light icons for dark themes

### ISSUE THREAD

**Issue by Aicaya** [MasterQ32/kristall#22]
I'm using the OS Default theme and the black icons can be hard to see depending on the area:

![Screenshot_20200622_132541](https://user-images.githubusercontent.com/17915907/85317424-5bfdc400-b48c-11ea-8d85-4da011288fea.png)

An option to switch icons to a white variant for dark theme users would help.

**Comment by MasterQ32** [comment]
Heya!

I'm actually working on that **right now**!

**Comment by MasterQ32** [comment]
I have added a white and a black icon set in 67633631b04c40db0affaadcdcf68068ed4357f7:
![](https://mq32.de/public/f8c63ef781cc69ff823bdd5e3556dca326d91394.png)

**Comment by Aicaya** [comment]
The icons look great on the dark theme, but I'll stick to 0.3 for now 'cause the update kinda breaks the OS Default theme:

![Screenshot_20200622_195502](https://user-images.githubusercontent.com/17915907/85346192-b3b72200-b4c2-11ea-89e7-a3964ab4d855.png)

Also, minor quirk of the latest git version: The settings option always starts on the Gemini TLS tab now.

**Comment by MasterQ32** [comment]
> The icons look great on the dark theme, but I'll stick to 0.3 for now 'cause the update kinda breaks the OS Default theme:

Yeah, `master` is the development branch. It's usually safe to use, but some stuff might be broken inbetween releases. I should add that to the README

> Also, minor quirk of the latest git version: The settings option always starts on the Gemini TLS tab now.
Yeah, i'm aware of that. It's just what the latest tab i have in the IDE opened was :D

**Comment by krkk** [comment]
@MasterQ32 This issue is not resolved yet — gopher map links are still light-theme only. I will take a look at it :)

**Comment by MasterQ32** [comment]
I'm waiting a lot on CI right now, so i can also take a look (i've also seen a fix already, only question is how to query the system preference for dark/light)
