### ISSUE TITLE
qttools5-dev-tools is now a build requirement

### ISSUE THREAD

**Issue by georgedorn** [MasterQ32/kristall#220]
Without it, you get:
`make: /usr/lib/qt5/bin/lrelease: Command not found`

Should probably add that to the ubuntu build instructions, possibly other platforms, too?

**Comment by HankG** [comment]
I was coming to add a comment about this too sort of. I too had the lrelease issue on Fedora 34 on aarch64 and resolved it by bringing in qt5-linguist package.

**Comment by MasterQ32** [comment]
I have added `qttools5-dev-tools` to Ubuntu dependencies in BUILDING.md, same for `qt5-linguist` to Fedora. This should be resolved now
