### ISSUE TITLE
Wrong host removed when revoking trust after sorting list

### ISSUE THREAD

**Issue by gestra** [MasterQ32/kristall#233]
Sorting the list in Settings -> Gemini TLS by Host Name, selecting a host to be removed and clicking Revoke trust causes a seemingly random host to be removed instead.

![hostname](https://user-images.githubusercontent.com/6391580/116785972-0a0ecd00-aaa5-11eb-844a-cb59c1e4a839.gif)

The only situation where the correct selected host is removed after sorting is when the list is sorted by First Seen in ascending order which seems to be the default sorting. Sorting by First Seen in descending order and selecting the top row causes the bottom row to be removed.

![firstseen](https://user-images.githubusercontent.com/6391580/116785974-0f6c1780-aaa5-11eb-9e4a-b3d64c8f4e1a.gif)

Built from 86959d55a041ad9bf113d0f600d8f0ad5e8220c8 on Fedora 33.

**Comment by mikejzx** [comment]
Should be fixed in #234 
Please try building from [mikejzx:master](https://github.com/mikejzx/kristall) to confirm :smiley:
