### ISSUE TITLE
Favourites not saved on exit on Windows

### ISSUE THREAD

**Issue by shunf4** [MasterQ32/kristall#235]
I am using nightly Windows version, downloaded today (May 24th, version 0.4).

- Run `kristall.exe`
- Do some changes to favorites, like adding a link, creating/deleting a group, etc.
- Quit Kristall
- Run Kristall again
- Changes to favorites are not reflected.

But I expect Kristall to remember my favourites.

A workaround would be saving Settings (by clicking "OK" in Settings dialog). That saves favourites as well.

**Comment by krkk** [comment]
Hi, 9a55d32e2c58fbc99e3043fd9ffc29fd62a37db3 (PR #225) already fixed this, but the binaries hadn't been updated yet (nginx says in headers that the files were last modified on 23th of March, which is probably the reason why it isn't here).

**Comment by xander-page** [comment]
I'm having the same problem on the nightly AppImage.

**Comment by mastazi** [comment]
Donwloaded nightly today and still having same issue.

**Comment by MasterQ32** [comment]
I will close this as resolved, as my CI was broken for some time. This was just a build issue, the build should be up to date
