### ISSUE TITLE
error on "make install"

### ISSUE THREAD

**Issue by kayew** [MasterQ32/kristall#24]
```
workdir/kristall - [tags/V0.3] » sudo make install
[sudo] password for sebastian:            
# Install icons
install -m 644 src/icons/kristall.svg /usr/local/share/icons/hicolor/scalable/apps/net.random-projects.kristall.svg
install: cannot create regular file '/usr/local/share/icons/hicolor/scalable/apps/net.random-projects.kristall.svg': No such file or directory
make: *** [Makefile:24: install] Error 1
workdir/kristall - [tags/V0.3] » 
```

**Comment by paolomi** [comment]
it happens to me too. You need to create the missing directories.  In Makefile add:
`install: kristall
	# Create target directories
	mkdir -p $(sharedir)/icons/hicolor/scalable/apps/
	mkdir -p $(sharedir)/icons/hicolor/16x16/apps/
	mkdir -p $(sharedir)/icons/hicolor/32x32/apps/
	mkdir -p $(sharedir)/icons/hicolor/64x64/apps/
	mkdir -p $(sharedir)/icons/hicolor/128x128/apps/
	mkdir -p $(sharedir)/applications/
	# Install icons
`
