### ISSUE TITLE
Update documentation to reflect current dependancies

### ISSUE THREAD

**Issue by dearman** [MasterQ32/kristall#246]
master no longer builds with Qt 5.9  lib/luis-l-gist/interactiveview uses QWheelEvent->angleDelta() which requires 5.15 I believe, but the Qt documentation is unclear.

**Comment by MasterQ32** [comment]
Huh, can you tell my why you closed the issue quickly after creating it?

**Comment by dearman** [comment]
My mistake.  It was just that same old issue with qmake again.  I didn't realize OpenSUSE still had the old Qt in it.  It dawned on my two seconds after hitting send when I saw (C) 2015 in the header file!
