### ISSUE TITLE
export certificate

### ISSUE THREAD

**Issue by paolomi** [MasterQ32/kristall#251]
In "Certificate Manager" I click on "Export certificate" then I select "Key file" and "Certificate file" but "Ok" button cannot be pressed.

**Comment by paolomi** [comment]
Now it works! The kristall binary is the same as two years ago, then maybe was it an issue in the QT libs? I don't know, but now I close this bug report

**Comment by Sophira** [comment]
I also had this issue just now. Looking at the code, it appears that the "OK" button won't get enabled unless both the key and certificate filenames end in either `.pem` or `.der`.

Thought I'd put this here in case it helps anyone in the future!
