### ISSUE TITLE
Automatic use of certificate?

### ISSUE THREAD

**Issue by ergodicbreak** [MasterQ32/kristall#254]
I'm not sure if my kristall is configured incorrectly, but after you create a cert the first time, is selecting that cert every time you visit a site expected?

![image](https://user-images.githubusercontent.com/3825386/154611634-00772305-c640-4170-8ac3-24715c15a198.png)

**Comment by MasterQ32** [comment]
Yes, this a design decision. You can add a pattern/regex to auto-enable your certificate on a certain site, but Kristall is designed privacy first and will never do things to compromise your identity without asking before doing so.

I also recommend to just make one certificate per site.

**Comment by ergodicbreak** [comment]
Thanks, I see what I overlooked in the cert manager now.
