### ISSUE TITLE
Bus error (core dumped)

### ISSUE THREAD

**Issue by ryliejamesthomas** [MasterQ32/kristall#26]
Getting this same error when trying both the release and master branch (Arch linux):

`Bus error (core dumped)`

Here's some info from the core dump:

master branch:

```
Stack trace of thread 2856621:
#0  0x00007f88d4f6774c gst_update_registry (libgstreamer-1.0.so.0 >
#1  0x00007f88d4efc0af n/a (libgstreamer-1.0.so.0 + 0x390af)
#2  0x00007f88d932a4c8 g_option_context_parse (libglib-2.0.so.0 + >
#3  0x00007f88d4ef38dd gst_init_check (libgstreamer-1.0.so.0 + 0x3>
#4  0x00007f88d4ef3985 gst_init (libgstreamer-1.0.so.0 + 0x30985)
#5  0x00007f88d509bec3 n/a (libgstmediaplayer.so + 0x8ec3)
#6  0x00007f88db11f06f n/a (libQt5Multimedia.so.5 + 0x5506f)
#7  0x00007f88db15d84e _ZN12QMediaPlayerC2EP7QObject6QFlagsINS_4Fl>
#8  0x0000564aa7bd9a33 n/a (/home/rjt/.local/bin/kristall/kristall>
#9  0x0000564aa7bb375a n/a (/home/rjt/.local/bin/kristall/kristall>
```
 release

```
Stack trace of thread 2933655:
#0  0x00007f810016474c gst_update_registry (libgstreamer-1.0.so.0 + 0xa474c)
#1  0x00007f81000f90af n/a (libgstreamer-1.0.so.0 + 0x390af)
#2  0x00007f81041574c8 g_option_context_parse (libglib-2.0.so.0 + 0x604c8)
#3  0x00007f81000f08dd gst_init_check (libgstreamer-1.0.so.0 + 0x308dd)
#4  0x00007f81000f0985 gst_init (libgstreamer-1.0.so.0 + 0x30985)
#5  0x00007f810039eec3 n/a (libgstmediaplayer.so + 0x8ec3)
#6  0x00007f8105f4c06f n/a (libQt5Multimedia.so.5 + 0x5506f)
#7  0x00007f8105f8a84e _ZN12QMediaPlayerC2EP7QObject6QFlagsINS_4FlagEE (libQt5Mul
#8  0x000055f87c82f603 n/a (/home/rjt/.local/bin/kristall-0.3/kristall + 0x4d603)
#9  0x000055f87c80ec0f n/a (/home/rjt/.local/bin/kristall-0.3/kristall + 0x2cc0f)
```

_almost_ identical

Let me know if there's any other info I could give you that might help.

**Comment by MasterQ32** [comment]
Can you tell me when this happens?
I'm using arch myself and i don't have problems, so we probably have some different packages installed...

**Comment by ryliejamesthomas** [comment]
Oh sorry. This happens when I try to start the program. It doesn't open at all.

**Comment by ryliejamesthomas** [comment]
If it helps here're the `qt5-` packages I have installed:

- qt5-base 5.15.0-4
- qt5-declarative 5.15.0-1
- qt5-graphicaleffects 5.15.0-1
- qt5-location 5.15.0-1
- qt5-multimedia 5.15.0-1
- qt5-quickcontrols 5.15.0-1
- qt5-quickcontrols2 5.15.0-1
- qt5-script 5.15.0-1
- qt5-sensors 5.15.0-1
- qt5-speech 5.15.0-1
- qt5-svg 5.15.0-1
- qt5-tools 5.15.0-2
- qt5-wayland 5.15.0-1
- qt5-webchannel 5.15.0-1
- qt5-webengine 5.15.0-4
- qt5-webkit 5.212.0alpha4-6
- qt5-websockets 5.15.0-1
- qt5-x11extras 5.15.0-1
- qt5-xmlpatterns 5.15.0-1

**Comment by ryliejamesthomas** [comment]
Not sure what changed, but it's now working fine!

You're welcome to close the issue.

**Comment by MasterQ32** [comment]
Ha! Fixing bugs by doing nothing. The best way!
