### ISSUE TITLE
Bug in manpage creation using dash

### ISSUE THREAD

**Issue by charles2910** [MasterQ32/kristall#274]
Hi, Felix. I'm here again :-)

So Debian links /bin/sh to /bin/dash to interpret commands. The problem is dash doesn't support different locales and it's breaking the `sed -E` command. Invoking bash explicitily solves the problem.

The problem:
![Screenshot from 2023-06-01 22-03-09](https://github.com/MasterQ32/kristall/assets/34252251/6465998c-fcf3-4d49-89bb-1f68c52eda6c)

Using `#!/bin/bash`:
![Screenshot from 2023-06-01 22-03-49](https://github.com/MasterQ32/kristall/assets/34252251/5b21890d-c5c8-44b9-97e5-b5f1d36e0f59)

Now, is it ok to change the hashbang to `/bin/bash`? I'm thinking about users outside Debian (like BSD and MacOS)

**Comment by MasterQ32** [comment]
This is actually a good question, i think we actually switched from `bash` to `sh` as it wasn't compatible to other systems. is `sed` a shell builtin in `dash`?

**Comment by charles2910** [comment]
we (sergiodj, samueloph and I) are suspecting the problem is in `echo` (which is a built in commad), not actually in `sed`. I'll try to do a debug session during the weekend to pinpoint the issue and report upstream. I thought "maybe I should try to report this quick and dirty fix before", but I see it might be a problem to other systems.

**Comment by charles2910** [comment]
Ok, I was able to pinpoint the problem:
![image](https://github.com/MasterQ32/kristall/assets/34252251/116e427b-4544-433c-9dd6-acf455ed70b0)

Double escaping seems to solve it in sh/dash, but it put 2 backslashs in bash. I'm not sure what is the correct/expected behavior in this case.

sh/dash:
```bash
$ echo $(echo press *Return* and | sed -E -e 's#(^|[.,!? ]+)[*_]([^*_ ]+[^*_]+[^*_ ]+)[*_]($|[.,!? ])#\1\\\\fI\2\\\\fR\3#g')
press \fIReturn\fR and
```

bash:
```bash
charles@x1-carbon:~$ echo $(echo press *Return* and | sed -E -e 's#(^|[.,!? ]+)[*_]([^*_ ]+[^*_]+[^*_ ]+)[*_]($|[.,!? ])#\1\\\\fI\2\\\\fR\3#g')
press \\fIReturn\\fR and

**Comment by charles2910** [comment]
Now I think I've found the answer. sh and, consequently, dash interpret some escaped characters as control sequences, so an `echo '\f'` outputs a form feed. bash's `echo` defaults to ignore escaped characters unless explicitly told otherwise (`-e` flag).

So, my question is: should we double escape `\f` to comply with dash? If you agree, I can open a PR with this fix:

```diff
diff --git a/doc/gen-man.sh b/doc/gen-man.sh
index 4463c5a..52b5132 100755
--- a/doc/gen-man.sh
+++ b/doc/gen-man.sh
@@ -59,8 +59,8 @@ gem_in=$(
     # First expression replaces all [Text like this] with bold text.
     # Second expression replaces text like *This* or _this_ with italic text.
     sed -E \
-      -e 's#\[([^]]*)\]#\\fB\1\\fR#g' \
-      -e 's#(^|[.,!? ]+)[*_]([^*_ ]+[^*_]+[^*_ ]+)[*_]($|[.,!? ])#\1\\fI\2\\fR\3#g'
+      -e 's#\[([^]]*)\]#\\\\fB\1\\\\fR#g' \
+      -e 's#(^|[.,!? ]+)[*_]([^*_ ]+[^*_]+[^*_ ]+)[*_]($|[.,!? ])#\1\\\\fI\2\\\\fR\3#g'
 )
 
 # Convert gemtext to man format
```

**Comment by MasterQ32** [comment]
Yeah, can you try make a PR?

**Comment by charles2910** [comment]
Yeah, of course!

**Comment by charles2910** [comment]
I think we can close this issue, right?
