### ISSUE TITLE
CMake support: 

### ISSUE THREAD

**Issue by trcwm** [MasterQ32/kristall#278]
Hi all! 

I compiled Kristall directly using CMAKE. In case you want to support it (I think Qt is moving away from qmake in the future), here is my setup. It works on Ubuntu 22.04 but haven't tested it on other platforms.

Kristall looks great btw! 

Regards, Niels.

[CMakeLists.txt](https://github.com/MasterQ32/kristall/files/11962645/CMakeLists.txt)
[cmake_dir.zip](https://github.com/MasterQ32/kristall/files/11962648/cmake_dir.zip)

**Comment by bkmgit** [comment]
This seems to have been incorporated in https://github.com/MasterQ32/kristall/blob/master/CMakeLists.txt
