### ISSUE TITLE
Build on Fedora 32

### ISSUE THREAD

**Issue by TahomaSoft** [MasterQ32/kristall#29]
To get the Makefile to work on Fedora 32, the command in the Makefile needs to be changed from qmake to qmake-qt5

**Comment by MasterQ32** [comment]
Can you try compiling with env variable `QT_SELECT=qt5` ?

**Comment by TahomaSoft** [comment]
Guten Morgen!
Unfortunately, that doesn't work, as there is no qmake by that name on a fedora 32 system. Instead, it is called qmake-qt5 (there is also a qmake-qt4). Setting that environment variable in the shell has no impact. 

However, a more portable change is to set a QMAKE environment variable in the Makefile, point it to the right executable, and that will work.  Sending you a pull request with that modification.

Vielen Danke!

**Comment by MasterQ32** [comment]
> Sending you a pull request with that modification.

Wonderful! Thanks!

**Comment by MasterQ32** [comment]
Pull request was merged
