### ISSUE TITLE
fatal error: optional: No such file or directory (Debian)

### ISSUE THREAD

**Issue by maluta** [MasterQ32/kristall#33]
I'm following the steps to build from source and after 'make' I got: 

**fatal error: optional: No such file or directory**

![image](https://user-images.githubusercontent.com/23658/86541882-fd523480-bee6-11ea-806f-4958d4c0444b.png)

I know that isn't directly related to Kristall but it can be worth for other users trying to build in the future 

I'm thinking about possible workarounds to that. My early test didn't fix the problem like modify the code to #include <experimental/optional> that produces another kind of errors...

![image](https://user-images.githubusercontent.com/23658/86541989-f841b500-bee7-11ea-929b-347ccb8fd4ee.png)

Maybe the solution will be updating my g++ (from 6.x to 7.x) but I'd like to check first if somebody here has a better idea. 

Thanks

**Comment by MasterQ32** [comment]
Yeah this means your c++ stdlib is too old. Installing a newer version (libstdc++7.1 or libc++4)

More information can be found here: https://en.cppreference.com/w/cpp/compiler_support

Used features in kristall are `std::optional` and if with initializer

**Comment by MasterQ32** [comment]
Could you resolve this issue?

**Comment by MasterQ32** [comment]
Kristall requires a C++17 compiler right now, so i will close this issue
