### ISSUE TITLE
Emojis don't display

### ISSUE THREAD

**Issue by makeworld-the-better-one** [MasterQ32/kristall#39]
This is with the latest master, on Arch Linux. I just get boxes for most emojis.

**Comment by makeworld-the-better-one** [comment]
It'd be nice if twemoji was included or something to guarantee emojis across all platforms and font setups.

**Comment by makeworld-the-better-one** [comment]
This bug appears to be caused by Kristall not switching fonts when an emoji is in the text. Most fonts don't support emojis, and so I can't get them to display. I was able to fix this by setting my font to one of the Noto Emoji fonts, but this isn't a long term solution.

**Comment by jagger27** [comment]
Interestingly, the behaviour on macOS is that fonts get an automatic override (apparently at the system level, not sure) and use Apple Color Emoji. ``

I think a patch to `src/documentstyle.cpp` in the DocumentStyle constructor roughly around line 155 like this should work:
```C++
DocumentStyle::DocumentStyle() : theme(Fixed),
    [...]
    h3_font.setFamily("sans");
    h3_font.setBold(true);
    h3_font.setPointSizeF(16.0);

    QStringList emojiFonts = { "Apple Color Emoji", "Segoe UI Emoji", "Twitter Color Emoji" };
    QFont::insertSubstitutions("sans", emojiFonts);
    QFont::insertSubstitutions("monospace", emojiFonts);
}
```

**Comment by jagger27** [comment]
Oh and I guess you'd also have to call `QFont::insertSubstitutions("Fancy User Font", emojiFonts);` on custom fonts somewhere too.

**Comment by makeworld-the-better-one** [comment]
Interesting solution. Doesn't rely on the user having one of those fonts installed though? Might be better to package one with Kristall. I also think it'd be good to add `Noto Color Emoji` there too.

**Comment by jagger27** [comment]
I agree, but I think it would be appropriate to leave the included font as the last failover so that the system emoji font first is used first. Perhaps that could be a setting as well.

I do think that the whole font and theming system needs a refactor though. The load/save/apply workflow is strange and buggy. I don't know where the theme files are stored, but they survive a recompile on my system. I wish that was a bit clearer. They're not in `~/.config` as far as I can see.

**Comment by MasterQ32** [comment]
Hey!
I'm kinda busy right now, but following the issues here anyways. `QFont::insertSubstitutions` sounds like a good solution to me

> Interesting solution. Doesn't rely on the user having one of those fonts installed though? Might be better to package one with Kristall. I also think it'd be good to add Noto Color Emoji there too.

Yeah that would've been my plan here. Package a emoji font and set it as substitutions.


>  The load/save/apply workflow is strange and buggy. I don't know where the theme files are stored, but they survive a recompile on my system. I wish that was a bit clearer. They're not in ~/.config as far as I can see.

Can you please make a separate issue for that? I tested loading/saving, but i changed a whole lot of stuff there. Themes are stored in `~/config/kristall/themes` as files, you should be able to drop the themes just in there...

**Comment by MasterQ32** [comment]
Basic emoji support has landed in 7f0143b87433a40b651a1ea582c7dcd2fd22660b. Can you all please test if it works for you?

**Comment by makeworld-the-better-one** [comment]
I built directly from that commit, and for some reason it shows all emojis in a line drawing format, even ones that aren't specced by Unicode as having a line drawn option.

![Screenshot_2020-08-17_09-46-35](https://user-images.githubusercontent.com/25111343/90403269-b5d6d080-e06e-11ea-8547-7acb846aa56a.png)

I am not sure why this is happening as it appears Kristall loads its own font files.

**Comment by makeworld-the-better-one** [comment]
@MasterQ32 Any idea about this? Still experiencing it with the latest commit be06c40292e011e5f9141af49d44530874636b50.
