### ISSUE TITLE
Client does not work with ed25519 server certificate 

### ISSUE THREAD

**Issue by jagger27** [MasterQ32/kristall#40]
The Go-based clients appear to have support through the standard library.

The certificate and key were generated and self signed with OpenSSL 1.1.1g:
`openssl req -x509 -newkey ed25519 -keyout key.pem -out cert.pem -days 365 -subj '/CN=localhost' -nodes`

I tested it locally with a custom server running the [Gig](https://github.com/pitr/gig) framework. 
`[gig-debug] gemini: tls: peer doesn't support any of the certificate's signature algorithms`

I'll poke around in [src/certificatehelper.cpp](https://github.com/MasterQ32/kristall/blob/master/src/certificatehelper.cpp) and some other places (not too familiar with it yet) to see if I can't get some other types working!

**Comment by MasterQ32** [comment]
I tried reproducing it on my local machine, generated a certificate with the provided command and used it with
```
echo -ne '40 FAILURE\r\n' | ncat --ssl-key key.pem --ssl-cert cert.pem -l 1234
```

I got no errors and it "just worked", so i cannot reproduce it here. Can you please provide a small example project with Gig, so i can test it easily?

**Comment by MasterQ32** [comment]
I tried reproducing the issue again and it seemed to work.
