### ISSUE TITLE
<hr> elements on HTML sites blend in on dark themes

### ISSUE THREAD

**Issue by Aicaya** [MasterQ32/kristall#41]
I use a very dark color scheme, so the default black color for the `<hr>` element blends in. I don't actually use kristall to browse http websites, but I *am* using it alongside Lynx to see how my site looks on HTML-only browsers, which is how I noticed:

![Screenshot_20200718_211357](https://user-images.githubusercontent.com/17915907/87864913-3f926180-c93c-11ea-823f-962a33ab176d.png)

(Link censored since the site is also for my artwork and the content is inappropriate.)

I think having it be the same color as one of the other elements would be a good fix (maybe either the text or the blockquote background).

**Comment by ryliejamesthomas** [comment]
For reference, the `<hr>` unstyled takes the main colour, the same as borders, text, etc. That is what I would expect, from a web-design perspective.

**Comment by MasterQ32** [comment]
I could try including a custom Qt stylesheet for HTML files, this could solve problems like this

**Comment by mikejzx** [comment]
This seems to be a bit of a pain to implement. Qt doesn't allow us to alter the colour of a `<hr>` tag using stylesheets so some kind of workaround will be needed.
