### ISSUE TITLE
HTML rendering limitations?

### ISSUE THREAD

**Issue by felixp7** [MasterQ32/kristall#50]
I just gave Kristall 0.3 a whirl after learning about it yesterday (running the Linux AppImage if that helps), and couldn't help but notice that it renders certain web pages just fine, but shows only a blank screen for others. Contrast [my recent essay](https://felix.plesoianu.ro/web/site.html) versus [my homepage](https://felix.plesoianu.ro/).

It would be good to know what trips Kristall in the latter case. Thought it might be from my use of HTML5 structural elements, but the footer is rendered just fine in the former example. Thank you.

**Comment by felixplesoianu** [comment]
It will have to do, thanks!
