### ISSUE TITLE
Support mouse buttons 4 and 5 for back and forward

### ISSUE THREAD

**Issue by ryliejamesthomas** [MasterQ32/kristall#51]
Just noticed that I can't use the extra buttons on my mouse to move backwards and forwards in the history, as I usually can in browsers. It would be a nice addition :)

**Comment by MasterQ32** [comment]
I will try implementing this, but i cannot test it as i don't own a suitable 5-Button-Mouse

**Comment by ryliejamesthomas** [comment]
Thanks! Do you need to know which one is back and which is forward?

**Comment by zethra** [comment]
I'd also be willing to help gather info and or test for this.

**Comment by ryliejamesthomas** [comment]
Oh cool. I'm on 0.3, that explains it.

**Comment by jaynemo** [comment]
Button4 is typically treated as back and Button5 as forward. This is good training for keeping one's thumb in an ergonomic position when using a vertical mouse.
