### ISSUE TITLE
Redirect relative URL gives protocol violation (line too short for valid protocol)

### ISSUE THREAD

**Issue by Kevin-Sangeelee** [MasterQ32/kristall#59]
When I request the Client URL below, I get the corresponding Server response:

- C: gemini://localhost\r\n
- S: 31 /\r\n

Kristall responds with:

## Protocol Violation
The server did not serve the content you requested in a well-defined manner and Kristall could not process the data sent.
Line is too short for valid protocol

**Comment by MasterQ32** [comment]
Thanks for the report!

**Comment by nico202** [comment]
This happens because of #43 !

**Comment by MasterQ32** [comment]
Okay, good to know. I keep track of the issue in #43, closing this
