### ISSUE TITLE
Makefile: do not assume directories exist

### ISSUE THREAD

**Issue by nico202** [MasterQ32/kristall#66]
Hi! Build is going well until it tries to install icons.

On my system, /usr/share/icons/hicolor/ and subdirectories do not exist.
The simple workaround is obviously to create 

share/icons/hicolor/scalable/apps
share/icons/hicolor/16x16/apps
share/icons/hicolor/32x32/apps
share/icons/hicolor/64x64/apps
share/icons/hicolor/128x128/apps
share/applications

But if those could be created in the makefile it would maybe help others.

Thanks!

**Comment by MasterQ32** [comment]
What system are you using?

**Comment by nico202** [comment]
Ok I found that the new makefile creates them, but has not been tagged (I'm installing tag V0.3)

(The system is guix)

When will a new version be tagged?
Thanks, Nicolò

**Comment by MasterQ32** [comment]
> When will a new version be tagged?

Not sure, i should do it one day :see_no_evil:

**Comment by nico202** [comment]
In the meanwhile I noticed that the new build continuously try to run git command (I get a lot of git: command not found after each c++ invocation)

**Comment by MasterQ32** [comment]
Yes, the build uses `git` to determine the tag of the current version

**Comment by nico202** [comment]
I submitted the package for review to guix: https://issues.guix.gnu.org/44191
