### ISSUE TITLE
Code formatting not working properly (ascii, monospaced fonts)

### ISSUE THREAD

**Issue by ffuentese** [MasterQ32/kristall#68]
Trying to make ASCII art work (mostly for titles and make them a bit more catchy, lots of gemini sites use them) I tried to add one for my gemini site and found out that the notation "```" doesn't work well in Kristall. I have to say I modified my Kristall so that it used a monospace font. This is the example I'm using:

https://alex.flounder.online/example.gmi

```
    ,... ,...                                                
  .d' ".d' ""                           mm                   
  dM`  dM`                              MM                   
 mMMmmmMMm`7MM  `7MM  .gP"Ya `7MMpMMMbmmMMmm .gP"Ya  ,pP"Ybd 
  MM   MM   MM    MM ,M'   Yb  MM    MM MM  ,M'   Yb 8I   `" 
  MM   MM   MM    MM 8M""""""  MM    MM MM  8M"""""" `YMMMa. 
  MM   MM   MM    MM YM.    ,  MM    MM MM  YM.    , L.   I8 
.JMML.JMML. `Mbod"YML.`Mbmmd'.JMML  JMML`Mbmo`Mbmmd' M9mmmP'
```

I assume it should look well in Kristall too but it doesn't.

**Comment by MasterQ32** [comment]
What is your default *Preformatted Font*? I have `Source Code Pro` as my preformatted font and use `Fire Sans` as the normal font:
![Preview](https://mq32.de/public/c6a417420e576ebc80687e30013c6697593109d2.png)

>  have to say I modified my Kristall so that it used a monospace font.

What modifications did you do? What is your OS?

**Comment by ffuentese** [comment]
I solved it changing the font to another one. I had "monospace font" and 
it didn't work but I changed it to Lucida Sans as normal and Lucida 
Console as preformatted and it looks alright now.

**Comment by MasterQ32** [comment]
That sounds about right. I should check out the default fonts for different OSes
