### ISSUE TITLE
Feature Request: port kristall to the Genode operating system framework

### ISSUE THREAD

**Issue by baconicsynergy** [MasterQ32/kristall#71]
I love Genode - the Chromium browser via Falkon is beautiful, and I can spin up a virtual machine for more complicated stuff. What's really missing is a gopher/gemini browser, and kristall seems like the ideal choice as Genode has excellent support for Qt-based applications. purrrrhaps this could be done at some point in the future?

**Comment by MasterQ32** [comment]
Can you explain what Genode is? I could find a website, but i have zero experience with this. What would be required to support Genode?

**Comment by baconicsynergy** [comment]
I'll do my best to sum it up, I'm still learning a lot myself. Genode is a toolkit for building highly-secure component-based custom operating systems. It leverages various microkernels' capabilities and pushes everything else to userspace. It's designed to be microkernel agnostic - you can choose which microkernel suits you best. It's also very very scalable - you can launch a simple embedded program or an entire desktop OS (the desktop OS has a specific name - Sculpt). I like Sculpt.

Here is the unoffical Hardware Compatability List: https://usr.sysret.de/jws/genode/hcl.html

It seems like your primary dependencies from what I can tell are the Qt5 and openssl libraries, all of which is provided by Genode!  The Genode Foundations book is the absolute best place to get the scoop on what exactly you'll need to do to port your software or write new stuff: https://genode.org/documentation/genode-foundations/20.05/index.html

**Comment by baconicsynergy** [comment]
Of course, their mailing list is active and very helpful: https://genode.org/community/mailing-lists

**Comment by MasterQ32** [comment]
I don't have time to do this and learn Genode. If somebody has experience with Genode, please re-open this issue or file a PR.
