### ISSUE TITLE
Flatpak Support

### ISSUE THREAD

**Issue by KeironO** [MasterQ32/kristall#75]
Hey there,

I love this project, and would love to see it used by many other users.

Flatpak is a software utility for software deployment, package management, and application virtualization for Linux desktop computers.

https://flatpak.org/

Packaging with Flatpak would handle all Linux Distro, version, flavour problems :smile: 

Best wishes,

KeironO

**Comment by MasterQ32** [comment]
Heya!

I already have a packaging process for AppImage :)

You can download a AppImage version here: https://kristall.random-projects.net/download/Kristall-nightly-x86_64.AppImage

Is there any difference to Flatpak?

**Comment by MasterQ32** [comment]
I don't see any benefit in additionally providing a FlatPak build for Kristall right now. If anyone cares about this, please reopen this issue
