### ISSUE TITLE
crash in HTTP(s) when trying to access a folder with no trailing "/"

### ISSUE THREAD

**Issue by bmorel** [MasterQ32/kristall#79]
I have a crash in commit 0baa75b933db5c1d98da9833f687aff552f69268 on Debian 10 "buster", when coming from http://deadbeef.fr when clicking on any link which redirects on a folder, after having a dialog box saying:

```
The location you visited wants to redirect you to another host and switch the protocol.
Protocol: 
New Host: 
Do you want to allow the redirection?
```

Link could be, for example: `http://deadbeef.fr/random`. Those links are generated by darkhttp where there is no index.html file.

**Comment by MasterQ32** [comment]
Heya!

The reason this happens is that the redirection uses a local redirection without a host. I think Kristall is just missing the case to handle non-full url redirects

**Comment by bmorel** [comment]
Indeed. I suppose this implies you could prefix those links with the "local link prefix" too, when the crash will be fixed. I just discovered that feature and love it!
