### ISSUE TITLE
Alternative page layout

### ISSUE THREAD

**Issue by mikejzx** [MasterQ32/kristall#91]
Currently, Kristall displays pages by filling up the entire width of the window with text (shown below)

![kristall](https://user-images.githubusercontent.com/42143005/103194955-53071700-4935-11eb-8a9a-cfe74c45474d.png)

Other Gemini browsers such as Lagrange have an interesting feature where the text is actually clamped to a maximum width, and then centred on the page which I think is a easier to read for most people (can be an opt-in feature for those who like the old layout)

![lagrange](https://user-images.githubusercontent.com/42143005/103194973-61edc980-4935-11eb-8ff2-723415586522.png)

(I tried to get the themes the same to illustrate the formatting better)

It seems like the text is placed inside of a "container" that is set to have a maximum width (usually around 800px), and this container's width remains at this maximum value until the _parent window's size_ becomes smaller than it - in which case the container will have the same width as the parent.

Kristall uses a `QTextDocument` to display the pages. Since I'm not too experienced with Qt I can't say for sure whether this feature is implementable with the current setup, so some changes may have to be made

**Comment by MasterQ32** [comment]
Yes, it is implementable. You can afaik just set a maximumWidth on the QTextDocument or the viewer for it
